In [ ]:
# https://huggingface.co/transformers/v3.2.0/custom_datasets.html

In [ ]:
!pip install transformers -U

In [ ]:
import pandas as pd


In [ ]:

# file_path = "hindi.csv"
# df = pd.read_csv(file_path)

# # Map label names to integers
# label_map = {"positive": 0, "negative": 1, "neutral": 2}
# df['label'] = df['label'].apply(lambda x: label_map[x])
# print(df.head())



import pandas as pd

file_path = "hindi.csv"
df = pd.read_csv(file_path)

# Map label names to integers
label_map = {"positive": 0, "negative": 1, "neutral": 2}

# Update the lambda function to handle NaN values
df['label'] = df['label'].apply(lambda x: label_map.get(x, -1) if pd.notna(x) else x)
print(df.head())

# import pandas as pd

# # Define the file paths
# file_paths = ["tamil_train.tsv"]

# # Map label names to integers
# label_map = {"Positive": 0, "Negative": 1, "Mixed_feelings": 2, "unknown_state": 3, "not-Tamil": 4}

# # Read data from each file and concatenate
# dfs = []
# for file_path in file_paths:
#     # Read data
#     df = pd.read_csv(file_path, delimiter='\t')

#     # Map labels
#     df['category'] = df['category'].apply(lambda x: x.strip())  # Remove leading/trailing whitespaces
#     df['category'] = df['category'].apply(lambda x: label_map.get(x, -1))  # Map labels

#     dfs.append(df)

# # Concatenate dataframes
# combined_df = pd.concat(dfs, ignore_index=True)

# print(combined_df.head())


                                                text  label
0  लोग वतन तक खा जाते हैं इसका इसे यकीन नहींमान ज...      1
1  गुमनाम है वतन पर मिटने वाले लोग आतन्कवादियों स...      1
2  ज़ंजीर बदली जा रही थी मैं समझा था रिहाई हो गयी है      1
3  यूपी में बड़े स्तर पर दंगे करवा सकती है बीजेपी...      1
4  अंग्रेजी नहीं आती है इसलिए हिन्दी ट्विट ज्यादा...      1


In [ ]:
# data.to_csv("/content/drive/MyDrive/Youtube Tutorials/datasets/toxic_commnets.csv",index=False)

In [ ]:
df['text'].value_counts()

text
ससुर ने किया बलात्कार ISLAMIC LAW-NOW WIFE IS MOTHER इस्लामिक क़ानून-अब बीवी को माँ मानो                                                                8
जम्मू-कश्मीर बाढ़ : PM ने लिया हालात का जायजा 1000 करोड़ रुपए की दी आर्थिक सहायता - Zee News हिन्दी                                                     7
निर्दोष Asaram Bapu Ji को POCSO के गलत इस्तेमाल से फँसाया गया| Why Jodhpur Police let #365DaysOfPOCSOmisuse happen?                                     4
J&K: भूस्खलन में 7 की मौत 20 लापता: जम्मू-कश्मीर के उधमपुर जिले के एक सुदूर पर्वतीय गांव में भारी बारिश के बा                                           3
RT @theworldindex: World most polluted cities 2018:\n\n1.🇮🇳 Gurugram\n2.🇮🇳 Ghaziabad\n3.🇵🇰 Faisalabad\n4.🇮🇳 Faridabad\n5.🇮🇳 Bhiwadi\n6.🇮🇳 Noida\n7.…    3
                                                                                                                                                       ..
@vikasbha @narendramodi Kya baat... Suri... Chhaa gya... Hero hai ladka

In [ ]:
data = df[['text','label']]


In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score
import torch
from transformers import TrainingArguments, Trainer
from transformers import BertTokenizer, BertForSequenceClassification

In [ ]:
# from transformers import BertTokenizer, BertForSequenceClassification
# tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
# model = BertForSequenceClassification.from_pretrained('bert-base-uncased',num_labels=2)


from transformers import AutoTokenizer, AutoModelForSequenceClassification
tokenizer = AutoTokenizer.from_pretrained('ai4bharat/indic-bert')

X = tokenizer(df['text'].tolist(), padding=True, truncation=True, max_length=512, return_tensors='pt')

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


In [ ]:
model = AutoModelForSequenceClassification.from_pretrained('ai4bharat/indic-bert', num_labels=3)

pytorch_model.bin:   0%|          | 0.00/135M [00:00<?, ?B/s]

Some weights of AlbertForSequenceClassification were not initialized from the model checkpoint at ai4bharat/indic-bert and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [ ]:
sample_data = ["I am eating","I am playing "]
tokenizer(sample_data, padding=True, truncation=True, max_length=512)

{'input_ids': [[2, 7922, 472, 43931, 3, 0], [2, 7922, 472, 8408, 8, 3]], 'token_type_ids': [[0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 0], [1, 1, 1, 1, 1, 1]]}

In [ ]:
X = list(df["text"])
y = list(df["label"])
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2,stratify=y)
X_train_tokenized = tokenizer(X_train, padding=True, truncation=True, max_length=512)
X_val_tokenized = tokenizer(X_val, padding=True, truncation=True, max_length=512)

In [ ]:
X_train_tokenized.keys()

dict_keys(['input_ids', 'token_type_ids', 'attention_mask'])

In [ ]:
print(X_train_tokenized['attention_mask'][0])

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0]


In [ ]:
len(X_train),len(X_val)

(1534, 384)

In [ ]:
# Create torch dataset
class Dataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels=None):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        if self.labels:
            item["labels"] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.encodings["input_ids"])

In [ ]:
train_dataset = Dataset(X_train_tokenized, y_train)
val_dataset = Dataset(X_val_tokenized, y_val)

In [ ]:
train_dataset[5]

{'input_ids': tensor([     2,  48856,     98,  93897,     32,  31178,     21, 100597,   2323,
           5211,   1682,      8, 144354,  35162, 100478,  33892,  73559,     21,
             33,  32224,    686,  94675,  19054,  10529,    580,      9,   8217,
          50584,   2864,   2805, 132443,   1661,   3343,   2805,     32,  19078,
           2611,  15746, 117100,      3,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0]),
 'token_type_ids': tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [ ]:
def compute_metrics(p):
    print(type(p))
    pred, labels = p
    pred = np.argmax(pred, axis=1)

    accuracy = accuracy_score(y_true=labels, y_pred=pred)
    recall = recall_score(y_true=labels, y_pred=pred)
    precision = precision_score(y_true=labels, y_pred=pred)
    f1 = f1_score(y_true=labels, y_pred=pred)

    return {"accuracy": accuracy, "precision": precision, "recall": recall, "f1": f1}

In [ ]:
# # Define Trainer
# args = TrainingArguments(
#     output_dir="output",
#     num_train_epochs=1,
#     per_device_train_batch_size=8

# )
from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(
    output_dir='./results',          # output directory
    num_train_epochs=2,              # total number of training epochs
    per_device_train_batch_size=8,  # batch size per device during training
    per_device_eval_batch_size=16,   # batch size for evaluation
    warmup_steps=500,                # number of warmup steps for learning rate scheduler
    weight_decay=0.01,               # strength of weight decay
    logging_dir='./logs',            # directory for storing logs
    logging_steps=10,
)

trainer = Trainer(
    model=model,                         # the instantiated 🤗 Transformers model to be trained
    args=training_args,                  # training arguments, defined above
    train_dataset=train_dataset,         # training dataset
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics # evaluation dataset
)





trainer.train()

/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py:436: FutureWarning: Passing the following arguments to `Accelerator` is deprecated and will be removed in version 1.0 of Accelerate: dict_keys(['dispatch_batches', 'split_batches', 'even_batches', 'use_seedable_sampler']). Please pass an `accelerate.DataLoaderConfiguration` instead: 
dataloader_config = DataLoaderConfiguration(dispatch_batches=None, split_batches=False, even_batches=True, use_seedable_sampler=True)
  warnings.warn(


TrainOutput(global_step=384, training_loss=0.8965181472400824, metrics={'train_runtime': 38.3023, 'train_samples_per_second': 80.1, 'train_steps_per_second': 10.025, 'total_flos': 9309044055480.0, 'train_loss': 0.8965181472400824, 'epoch': 2.0})

In [ ]:
! pip install -U accelerate
! pip install -U transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 297.4/297.4 kB 5.9 MB/s eta 0:00:00
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl (166.0 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-many

In [ ]:
trainer.evaluate()

<class 'transformers.trainer_utils.EvalPrediction'>


ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].

In [ ]:
np.set_printoptions(suppress=True)

In [ ]:
text = "गुमनाम है वतन पर मिटने वाले लोग आतन्कवादियों से मिलकर मशहूर हो गये"
# text = "go to hell"
inputs = tokenizer(text,padding = True, truncation = True, return_tensors='pt').to('cuda')
outputs = model(**inputs)
print(outputs)
predictions = torch.nn.functional.softmax(outputs.logits, dim=-1)
print(predictions)
predictions = predictions.cpu().detach().numpy()
predictions

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.


SequenceClassifierOutput(loss=None, logits=tensor([[ 0.7745,  1.6292, -2.4814]], device='cuda:0',
       grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)
tensor([[0.2950, 0.6936, 0.0114]], device='cuda:0', grad_fn=<SoftmaxBackward0>)


array([[0.29503676, 0.6935903 , 0.01137299]], dtype=float32)

In [ ]:
trainer.save_model('CustomModel2')

In [ ]:
# trainer.save_model('/content/drive/MyDrive/Youtube Tutorials/toxic')
# model_2 = BertForSequenceClassification.from_pretrained("/content/drive/MyDrive/Youtube Tutorials/toxic")
# model_2.to('cuda')

In [ ]:

# from transformers import AutoTokenizer, AutoModelForSequenceClassification

# model_2 = AutoModelForSequenceClassification.from_pretrained("fine_tuning")
# model_2.to('cuda')

from transformers import AutoModelForSequenceClassification

model_2 = AutoModelForSequenceClassification.from_pretrained("CustomModel2")




# Move the model to the appropriate device (e.g., GPU if available)
device = 'cuda' if torch.cuda.is_available() else 'cpu'
model_2.to(device)


AlbertForSequenceClassification(
  (albert): AlbertModel(
    (embeddings): AlbertEmbeddings(
      (word_embeddings): Embedding(200000, 128, padding_idx=0)
      (position_embeddings): Embedding(512, 128)
      (token_type_embeddings): Embedding(2, 128)
      (LayerNorm): LayerNorm((128,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0, inplace=False)
    )
    (encoder): AlbertTransformer(
      (embedding_hidden_mapping_in): Linear(in_features=128, out_features=768, bias=True)
      (albert_layer_groups): ModuleList(
        (0): AlbertLayerGroup(
          (albert_layers): ModuleList(
            (0): AlbertLayer(
              (full_layer_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (attention): AlbertAttention(
                (query): Linear(in_features=768, out_features=768, bias=True)
                (key): Linear(in_features=768, out_features=768, bias=True)
                (value): Linear(in_features=768, out_features=768

In [ ]:
# text = "That was good point"
text = "लोग वतन तक खा जाते हैं इसका इसे यकीन नहींमान जाएगा तू ले जाकर दिल्ली इसे दिखा ला दोस्त"
inputs = tokenizer(text,padding = True, truncation = True, return_tensors='pt').to('cuda')
outputs = model_2(**inputs)
predictions = torch.nn.functional.softmax(outputs.logits, dim=-1)
predictions = predictions.cpu().detach().numpy()
predictions

array([[0.2869163 , 0.69707155, 0.01601219]], dtype=float32)

In [ ]:
#CustomModel Output-
array([[0.2257416 , 0.7594996 , 0.01475879]], dtype=float32)
# CustomModel2 Output-
array([[0.14694382, 0.8465548 , 0.00650142]], dtype=float32)



In [ ]:
import torch
print(torch.cuda.is_available())


False


In [ ]:

#EVALUATING MODEL
import numpy as np
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

import pandas as pd




file_path = "hindi sentiment analysis.csv"
df = pd.read_csv(file_path)
df = df.dropna()

# Map label names to integers
label_map = {"positive": 0, "negative": 1, "neutral": 2}

# Update the lambda function to handle NaN values
df['label'] = df['label'].apply(lambda x: label_map.get(x, -1) if pd.notna(x) else x)
print(df.head())


# Load tokenizer and model
tokenizer = AutoTokenizer.from_pretrained('ai4bharat/indic-bert')
model_2 = AutoModelForSequenceClassification.from_pretrained("fine_tuned_model")

# Move the model to the appropriate device (e.g., GPU if available)
device = 'cuda' if torch.cuda.is_available() else 'cpu'
model_2.to(device)

# Load your evaluation dataset
# Assuming you have X_eval as input texts and y_eval as corresponding labels



X = tokenizer(df['text'].tolist(), padding=True, truncation=True, max_length=512, return_tensors='pt')
X = list(df["text"])
y = list(df["label"])
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2,stratify=y)
X_train_tokenized = tokenizer(X_train, padding=True, truncation=True, max_length=512)
X_val_tokenized = tokenizer(X_val, padding=True, truncation=True, max_length=512)

# Tokenize the evaluation dataset
eval_inputs = tokenizer(X_val, padding=True, truncation=True, return_tensors='pt')

# Move inputs to the appropriate device
eval_inputs = {key: val.to(device) for key, val in eval_inputs.items()}

# Generate predictions
with torch.no_grad():
    outputs = model_2(**eval_inputs)
    predictions = torch.nn.functional.softmax(outputs.logits, dim=-1)
    predictions = predictions.detach().cpu().numpy()

# Convert probabilities to predicted labels
predicted_labels = np.argmax(predictions, axis=1)

# Compute evaluation metrics
accuracy = accuracy_score(y_val, predicted_labels)
recall = recall_score(y_val, predicted_labels, average='weighted')
precision = precision_score(y_val, predicted_labels, average='weighted')
f1 = f1_score(y_val, predicted_labels, average='weighted')

print("Accuracy:", accuracy)
print("Recall:", recall)
print("Precision:", precision)
print("F1-score:", f1)
